### ISSUE TITLE
garlicoind (No testnet option) testnet assertion failing

### ISSUE THREAD

**Issue by quantumproducer** [GarlicoinOrg/Garlicoin#13]
I cloned from this repository.
Compiled with: `./autogen.sh && ./configure --without-gui --disable-tests && make && sudo make install`
now I run `garlicoind` and:

```
 garlicoind
garlicoind: chainparams.cpp:213: CTestNetParams::CTestNetParams(): Assertion `consensus.hashGenesisBlock == uint256S("0x69441a7748fdbef3cfedfca0e56a565394a15271da511dbe6ea58bb99930ef6e")' failed.
Aborted (core dumped)
```

**Comment by jdleo** [comment]
your garlicoin.conf file should have this:  
`testnet=0 `
Thank you!  
For *nix users, you your conf file is located at:  
`~/.garlicoin/garlicoin.conf`

**Comment by quantumproducer** [comment]
That fixes it on linux, thank you!
