### ISSUE TITLE
List addresses?

### ISSUE THREAD

**Issue by quantumproducer** [GarlicoinOrg/Garlicoin#14]
How can I list addresses from `garlicoin-cli`?
I see if I know my address I can do 

```
garlicoin-cli setaccount GRKWdn3RQZWdEQTESJsrjzSj1mTBCcbUMY main
garlicoin-cli getbalance main
```

but how would I get my address if I didn't save it from earlier?

**Comment by silonc** [comment]
@quantumproducer garlicoin-cli listreceivedbyaddress 0 true

**Comment by quantumproducer** [comment]
Oh, thank you. I wish ther was an easy way to see address > balance.
