### ISSUE TITLE
Garlicoind doesn't handle ctrl+c

### ISSUE THREAD

**Issue by dylmye** [GarlicoinOrg/Garlicoin#15]
#### If so, please list the steps to reproduce below:
1. Run `Garlicoind`
2. Press ctrl+c combination

### Expected behaviour
The application should ask if you wish to quit.

### Actual behaviour
```
terminate called after throwing an instance of 'std::bad_cast'
  what():  std::bad_cast

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
```

### Screenshots.
n/a - cli

### What version of garlicoin-core are you using?
20180121185844-arm-linux-gnueabihf

### Machine specs:
- OS: Windows 10
- CPU: Ryzen 1600
- RAM: 2x8gb DDR4-2400
- Disk size: 1TB
- Disk Type (HD/SDD): SSD

### Any extra information that might be useful in the debugging process.
Please request any if needs be

**Comment by opticalgenesis** [comment]
Both Ctrl-C and closing the window gives a crash on Windows 10 x64 as well

**Comment by quantumproducer** [comment]
On Linux it runs in background. Not expected..
Expected to start a new screen session with `screen -S garlicd` then do `garlicoind` then hit control+a, control+d to detach

**Comment by ryan-shaw** [comment]
@quantumproducer It doesn't run as a daemon, it runs in the foreground but just logs elsewhere, what you can do is add `-printtoconsole` if you want logging to stdout.

**Comment by dylmye** [comment]
https://stackoverflow.com/questions/1641182/how-can-i-catch-a-ctrl-c-event-c

https://docs.microsoft.com/en-us/windows/console/setconsolectrlhandler

https://github.com/bitcoin/bitcoin/issues/9746

Hope this helps!

**Comment by ryan-shaw** [comment]
@dylmye I don't think catching is the problem

**Comment by dylmye** [comment]
WDYT is the cause? It's certainly related to the termination routine

**Comment by ryan-shaw** [comment]
https://github.com/bitcoin/bitcoin/pull/9817/files

**Comment by dylmye** [comment]
It's possible even though that's for a segfault. I can post the thread call stack later if that helps

**Comment by ezquire** [comment]
We can probably close this it has been a bitcoin issue for a long time
https://github.com/bitcoin/bitcoin/issues/471

**Comment by dylmye** [comment]
Can you do something like "press q to quit"?

**Comment by VhatAmI** [comment]
@ezquire but if it gets fixed we can say GRLC > BTC

**Comment by ezquire** [comment]
i'm not sure it can be fixed very easily and for such a small issue it would probably be way more work to refactor the code to handle interrupts, but again im a newbie so i'm not sure
