### ISSUE TITLE
Can I get the following values?

### ISSUE THREAD

**Issue by ktechmidas** [GarlicoinOrg/Garlicoin#20]
I need them to port some code over from LTC:

pubkeyhash: 0x30,
privatekey: 0xb0,
scripthash: 0x32,
xpubkey: 0x019da462,
xprivkey: 0x019d9cfe,
networkMagic: 0xfbc0b6db,
port: 9333

The only know I really know is the port... does anyone have any idea what the rest should be? Which have changed and which haven't?

**Comment by smiba** [comment]
networkMagic is: 0xd2c6b6db

**Comment by ryan-shaw** [comment]
`0xd2c6b6db` is correct https://github.com/GarlicoinOrg/Garlicoin/blob/master/src/chainparams.cpp#L114

port `42069` not sure about others.

**Comment by ryan-shaw** [comment]
Ok finally had time to look at this in more depth:
pubkeyhash: `0x26`
privatekey: `0xb0`
scripthash: `0x32`
xpubkey: `0x0488b21e`
xprivkey: `0x0488ade4`
networkMagic: `0xd2c6b6db`

**Comment by ktechmidas** [comment]
Brilliant, thank you @ryan-shaw , really helpful!

**Comment by ktechmidas** [comment]
Would you mind telling me how you got the values? (If you have a bit of time) I couldn't figure it out

**Comment by ryan-shaw** [comment]
Most of them are in `src/chainparams.cpp`
