### ISSUE TITLE
dumpprivkey "Error: Please enter the wallet passphrase with walletpassphrase first."

### ISSUE THREAD

**Issue by quantumproducer** [GarlicoinOrg/Garlicoin#22]
I've dumped my privatekey previously with garlicoin-cli dumpprivkey ADDRESS
now I try this and I get this message.

Have I been hacked? I didn't git pull recently

**Comment by ryan-shaw** [comment]
You must have ran `encryptwallet` you need to run `walletpassphrase` (reference: https://en.bitcoin.it/wiki/Original_Bitcoin_client/API_calls_list)

**Comment by quantumproducer** [comment]
I never ran encryptwallet....

**Comment by ryan-shaw** [comment]
Well something/someone has

**Comment by quantumproducer** [comment]
Well, shit. Thank you.

**Comment by quantumproducer** [comment]
@ryan-shaw I ctrl+r `garlicoin-cli` all the way back to when I was running testnet commands. No mention of encrypt wallet until today trying to decrypt it.
