### ISSUE TITLE
Error parsing JSON sending

### ISSUE THREAD

**Issue by quantumproducer** [GarlicoinOrg/Garlicoin#23]
garlicoin-cli sendfrom main GSuffZcm7h6F3B2KfdZwzwQKSdf9r8MDw8 .1
error: Error parsing JSON:.1
garlicoin-cli sendfrom "main" "GSuffZcm7h6F3B2KfdZwzwQKSdf9r8MDw8" .1
error: Error parsing JSON:.1

**Comment by ryan-shaw** [comment]
Can you try 0.1 instead?

**Comment by retosen** [comment]
Try not using quotation marks in your commands. They shouldn't be necessary.

**Comment by quantumproducer** [comment]
Thanks, I tried. Running into https://github.com/GarlicoinOrg/Garlicoin/issues/22 .
