### ISSUE TITLE
Error when running garlicoind on Kubuntu 17.10

### ISSUE THREAD

**Issue by 0xjmux** [GarlicoinOrg/Garlicoin#25]
This issue tracker is only for technical issues related to garlicoin-core.

General garlicoin questions and/or support requests and are best directed to the [garlicointalk.io forums](https://garlicointalk.io/).

For reporting security issues, please contact the Garlicoin developers on the #garlicoin-dev Freenode IRC channel or alternatively you can email us at contact@garlicoin.org.

### Describe the issue
I get the following error: 
`garlicoind: chainparams.cpp:125: CMainParams::CMainParams(): Assertion `consensus.hashGenesisBlock == uint256S("0x")' failed.
Aborted (core dumped)`

#### If so, please list the steps to reproduce below:
1. I try to run garlicoind to set up a wallet
2.I get an error
3.No garlic for me

### Expected behaviour
I should start the garlicoind daemon

### What version of garlicoin-core are you using?

Garlicoin Core Daemon version v0.16.0.1-ed3ff80
Official binary, I downloaded from the official garlicoin.io site.

**Comment by ryan-shaw** [comment]
You aren't building from HEAD, you are building from ed3ff80

**Comment by 0xjmux** [comment]
How do I pick HEAD instead of ed3ff80?

**Comment by ryan-shaw** [comment]
~`git pull` if you are building from source.~ Download the latest binaries from the release section - https://github.com/GarlicoinOrg/Garlicoin/releases

**Comment by retosen** [comment]
@GarrukApex are you still getting the error, or can I close this?

**Comment by 0xjmux** [comment]
Close it please. The error is resolved.
