### ISSUE TITLE
Version number not being incremented on release

### ISSUE THREAD

**Issue by ryan-shaw** [GarlicoinOrg/Garlicoin#26]
The version number is not being incremented on release, this means the DNS seeder is reporting same version strings for all clients even if they are from different releases.

My suggestion would to have a [release] commit message required to build on CI and in this commit version numbers in `/src/config/bitcoin-config.h` are updated to appropriate values

edit: Also loving the project, first crypto related PRs for me :)

**Comment by ryan-shaw** [comment]
Also, I think releases should be very infrequent so node don't get too mismatched.

**Comment by aaruel** [comment]
Good point, also, releases after this will be infrequent as the critical things we wanted to have fixed are fixed. 

To your suggestion of versioning with the `bitcoin-config.h` file, basically you mean updating the version defines [here](https://github.com/GarlicoinOrg/Garlicoin/blob/master/configure.ac#L3) before committing a release version?

Also, thank you for all your work!

**Comment by ryan-shaw** [comment]
Yes, those defines look like the place. 

No problem! Happy to support the GRLC community. I plan on setting up a DNS seeder for testnet, do you you have nodes currently running on testnet at the moment? 

(I'll create a new PR with the DNS seed I'll add for testnet but it won't be active yet)

**Comment by ezquire** [comment]
Might want to change the copyright year as well :) its 2018 thanks for all your work on this guys i've been trying to find ways to help

**Comment by ryan-shaw** [comment]
@aaruel there were 2 builds yesterday for very minor changes, I don't think these were necessary?
