### ISSUE TITLE
mac app icon still lightcoin logo

### ISSUE THREAD

**Issue by ravenbyron** [GarlicoinOrg/Garlicoin#29]
### Describe the issue
When running the Garlicoin-qt app the icon in the app bar is still light coin logo. 

<img width="114" alt="screen shot 2018-01-25 at 10 52 59 am" src="https://user-images.githubusercontent.com/6773458/35400998-f187150a-01bd-11e8-94d6-fb41f0594894.png">

**Comment by ezquire** [comment]
http://doc.qt.io/archives/qt-4.8/appicon.html#setting-the-application-icon-on-mac-os-x

not sure if you want to do this

**Comment by ezquire** [comment]
might be able to just replace bitcoin.png and bitcoin.ico in the res files but since I don't have those I can't
