### ISSUE TITLE
Garlicoind 64bit for windows does NOT download blocks

### ISSUE THREAD

**Issue by bushshrub** [GarlicoinOrg/Garlicoin#30]
This issue tracker is only for technical issues related to garlicoin-core.

General garlicoin questions and/or support requests and are best directed to the [garlicointalk.io forums](https://garlicointalk.io/).

For reporting security issues, please contact the Garlicoin developers on the #garlicoin-dev Freenode IRC channel or alternatively you can email us at contact@garlicoin.org.

### Describe the issue
Garlicoind 64bit version on windows does not download the blocks
### Can you reliably reproduce the issue?
Yes
#### If so, please list the steps to reproduce below:
1. Download 64bit version of garlicoin core
2. Download wallet-win.zip
3. Run garlicoind once
4. Copy config file to `%appdata%\Garlicoin`
5. Close, then open garlicoind (with Ctrl-C) via the batch file
6. Check garlicoin-cli.exe getinfo

### Expected behaviour
Blocks should be downloading and number of blocks should start increasing

### Actual behaviour
No blocks download  at all.

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of garlicoin-core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.
https://github.com/GarlicoinOrg/Garlicoin/releases/tag/20180123154915-i686-pc-linux-gnu

### Machine specs:
- OS: Windows 10 Pro
- CPU: Intel Core i7-6700K @ 4.0GHz
- RAM: 16GB (2x8) Corsair Vengeance LPX DDR4-3000
- Disk size: Drive 0: Samsung 850 EVO 500GB Drive 1: Seagate Barracuda 7200 RPM 2TB
- Disk Type (HD/SDD): Drive 0: SSD Drive 1: HDD

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by ryan-shaw** [comment]
Can you provide the debug.log please

**Comment by bushshrub** [comment]
I lost that because it started downloading the new network :/

**Comment by ryan-shaw** [comment]
It's an append only log, so as long as you didn't delete it all will be there.

**Comment by bushshrub** [comment]
Yeah I deleted it :/

Try replicating the issue? It happens with that version specifically

**Comment by ryan-shaw** [comment]
Will try later today
