### ISSUE TITLE
No Garlicoin QT in the Windows x64 version

### ISSUE THREAD

**Issue by ktechmidas** [GarlicoinOrg/Garlicoin#34]
I only ask because it is in the Linux version, and it may stop a lot of people having to get external (3rd party) wallets if included in the Windows version too.

Was it just forgotten or was there a reason it isn't in here?

**Comment by AtoxIO** [comment]
+1

**Comment by araviel** [comment]
We needs gui for windows please, thanks :)

Or at least a readme for sync and creating address

**Comment by ryan-shaw** [comment]
This is done - https://github.com/GarlicoinOrg/Garlicoin/releases/tag/allium-mainnet
