### ISSUE TITLE
Request: publish source code of the Garlicoin airdrop website

### ISSUE THREAD

**Issue by dessant** [GarlicoinOrg/Garlicoin#35]
I've been following the issues you've had with making the Garlicoin airdrop work in the past week, it seems the help of the community could make things better. Could you push the code to a new repo under https://github.com/GarlicoinOrg?

Even if you end up fixing it tomorrow, it could still be a benefit to others who want to set up a similar service in the future.

**Comment by aaruel** [comment]
Definitely agree. The developer working on the airdrop just went to bed but said he will push to a repo tomorrow. Thank you for the suggestion! I will keep this issue open until the airdrop is released and completed.

**Comment by dessant** [comment]
@aaruel, do you have an update regarding the source code?

**Comment by ryan-shaw** [comment]
@dessant I imagine it will be published when the airdrop goes live or after it is done

**Comment by dessant** [comment]
@ryan-shaw, it's not clear, though the purpose of the request was to remove the developer bottleneck and be able to offer our help and fix the bugs they've encountered.
